name: Docker Image CI
on:
  workflow_dispatch: 
       inputs:
          tag:
            type: text
            required: true
            description: please enter image tag name
          environment:
            type: environment  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}   
    defaults:
     run:
        shell: bash     
    steps:
    - name: User selections
      run: echo "user selected environment  ${{ github.event.inputs.environment }}"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        architecture: x64
    - name: maven build
      run : mvn clean package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

          
    - name: Build & Push the Docker image
      run: |
        docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/next-project1-backend:${{github.event.inputs['tag']}}  
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/next-project1-backend:${{github.event.inputs['tag']}}  
      
        
